[package]
name = "infrastructure"
version.workspace = true
description.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
publish.workspace = true
documentation.workspace = true
repository.workspace = true

[dependencies]
serde = {workspace = true,features = ["derive"]}
tracing-appender.workspace = true
tracing-subscriber ={workspace = true,features = ["std", "fmt", "env-filter", "tracing-log", "time", "local-time", "json"]}
figment = {workspace = true,features = ["env", "toml"] }
lettre = {workspace = true, default-features = false,features = ["tokio1-rustls-tls","serde","smtp-transport","builder"] }
salvo.workspace = true
app_error = {path = "../app_error"}
services = {path = "../services"}

aws-sdk-s3 = {workspace = true,features = ["rt-tokio"]}
aws-config = {workspace = true,features = ["behavior-version-latest"]}
typedef = {path = "../typedef"}