[package]
name = "db"
version.workspace = true
description.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
publish.workspace = true
documentation.workspace = true
repository.workspace = true

[dependencies]
sqlx= { workspace = true,features = ["postgres"] }
infrastructure ={path = "../infrastructure"}
