[package]
name = "server"
version.workspace = true
description.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
keywords.workspace = true
homepage.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
salvo= { workspace = true, features = ["anyhow","rustls","quinn"] }
tokio= { workspace = true,features = ["full"] }
app_error ={path = "../app_error"}
db = {path = "../db"}
infrastructure = {path = "../infrastructure"}
routers = {path = "../routers"}
services = {path = "../services"}
typedef = {path = "../typedef"}
utils = {path = "../utils"}
tracing.workspace = true
